## Tensors

* constant tensor `tf.constant()`
    * Value of tensor never changes, hence *constant*.
    * `tf.constant(1234)` is a 0-dimensional int32 tensor
    * `tf.constant([1,2,3,4])` is a 4-dimensional int32 tensor

Sample code:

In [1]:
import tensorflow as tf

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

## Session
* An environment for running a graph. In charge of allocating the operations to GPU(s) and/or CPU(s).

Continuing our example:

In [3]:
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


## Input

* `tf.placeholder()`: returns a tensor that gets it’s value from data passed to the `tf.session.run()` function, allowing you to set the input right before the session runs.
* `feed_dict`: Use the feed_dict parameter in tf.session.run() to set the placeholder tensor. 

Example: 


In [4]:
a = tf.placeholder(tf.string)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.float32)
with tf.Session() as sess:
    output = sess.run(a, feed_dict={a: 'hi', b: 23, c: 32.0})
    print(output)

hi


It also works if you feed it only `{a: 'hi'}`, i.e. the relevant placeholder value(s).


## Maths

In [9]:
# Add, subtract, multiply and divide operations
add = tf.add(5, 2) # 7
sub = tf.sub(10, 4) # 6
mul = tf.mul(2, 5)  # 10
div = tf.div(10, 5) # 2

with tf.Session() as sess:
    output = [sess.run(add), sess.run(sub), sess.run(mul), 
              sess.run(div)]
    print(output)

[7, 6, 10, 2]


[TF Math documentation](https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops.html)

## Variables

* `tf.Variable()` function creates a tensor with an initial value that can be modified later, much like a normal Python variable. This tensor stores it’s state in the session, so you must use the `tf.initialize_all_variables()` function to initialize the state of the tensor.


In [14]:
# Initialisation

def variables():
    output = None
    
    x = tf.Variable([1, 2, 3, 4])
    
    # Initialise all variables
    init = tf.initialize_all_variables()
    
    with tf.Session() as sess:
        sess.run(init)
        output = sess.run(x)
    
    return output

variables()

array([1, 2, 3, 4], dtype=int32)

In [13]:
# Logistic Regression

def logits():
    output = None
    x_data = [[1.0, 2.0], [2.5, 6.3]]
    test_weights = [[-0.3545495, -0.17928936], [-0.63093454, 0.74906588]]
    class_size = 2
    
    
    x = tf.placeholder(tf.float32)
    weights = tf.Variable(test_weights)
    biases = tf.Variable(tf.zeros([class_size]))
    
    # ToDo: Implement wx + b in TensorFlow
    logits = tf.matmul(weights, x)
    
    init = tf.initialize_all_variables()
    with tf.Session() as sess:
        sess.run(init)
        output = sess.run(logits, feed_dict={x: x_data})
        
    return output

logits()

array([[-0.80277288, -1.83862185],
       [ 1.24173021,  3.4572463 ]], dtype=float32)

## Softmax

Turns logits into probabilities that sum to 1.
* `tf.nn.softmax()`.

Example of how it works:

```
# logits is a one-dimensional array with 3 elements
logits = [1.0, 2.0, 3.0]
# softmax will return a one-dimensional array with 3 elements
print softmax(logits)

[ 0.09003057  0.24472847  0.66524096]

# logits is a two-dimensional array
logits = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
# softmax will return a two-dimensional array with the same shape
print softmax(logits)


[
    [ 0.09003057  0.00242826  0.01587624  0.33333333]
    [ 0.24472847  0.01794253  0.11731043  0.33333333]
    [ 0.66524096  0.97962921  0.86681333  0.33333333]
]
```

In [ ]:
# Softmax function in ram Python

import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    # TODO: Compute and return softmax(x)
    # S(y_i) = (e**(y_i) / sum_over_j(e**y_j))
    return np.exp(x) / np.sum(np.exp(x), axis=0)

That's some elegant Numpy code.

In [ ]:
# Softmax with TF

import tensorflow as tf


def run():
    output = None
    logit_data = [2.0, 1.0, 0.1]
    logits = tf.placeholder(tf.float32)
    
    # ToDo: Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)    
    
    with tf.Session() as sess:
        # ToDo: Feed in the logits data
        output = sess.run(softmax, feed_dict={logits: logit_data})

    return output

Scaling and Softmax
* When you divide all the logits by e.g. 10, the probabilities get closer to the uniform distribution.
* When you multiply all the logits by e.g. 10, the probabilities get closer to 0.0 or 1.0.

## One-Hot Encodings
* Vectors with one 1.0 and 0.0 everywhere else.
